### ISSUE TITLE
Error on Kafka installation

### ISSUE THREAD

**Issue by rolmovel** [keedio/buildoopRecipes#60]
After installing kafka, trying to create a topic gets next error:

[command]
/usr/lib/kafka/bin/kafka-create-topic.sh --topic test --zookeeper master.rolmo:2181 --replica 2

[error]
[root@slave1 ~]# /usr/lib/kafka/bin/kafka-create-topic.sh --topic test --zookeeper master.rolmo:2181 --replica 2

log4j:ERROR Could not read configuration file from URL [file:/usr/lib/kafka/bin/../config/tools-log4j.properties].

java.io.FileNotFoundException: /usr/lib/kafka/bin/../config/tools-log4j.properties (No existe el fichero o el directorio)

at java.io.FileInputStream.open(Native Method)

at java.io.FileInputStream.<init>(FileInputStream.java:146)

at java.io.FileInputStream.<init>(FileInputStream.java:101)

at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)

at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)

at java.net.URL.openStream(URL.java:1037)

at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:459)

at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:471)

at org.apache.log4j.LogManager.<clinit>(LogManager.java:125)

at org.apache.log4j.Logger.getLogger(Logger.java:118)

at org.I0Itec.zkclient.ZkClient.<clinit>(ZkClient.java:57)

at kafka.admin.CreateTopicCommand$.main(CreateTopicCommand.scala:73)

at kafka.admin.CreateTopicCommand.main(CreateTopicCommand.scala)

log4j:ERROR Ignoring configuration file [file:/usr/lib/kafka/bin/../config/tools-log4j.properties].

log4j:WARN No appenders could be found for logger (org.I0Itec.zkclient.ZkConnection).

log4j:WARN Please initialize the log4j system properly.

creation succeeded!

**Comment by mvalleavila** [comment]
Fixed in openbus-1.1.2
